### ISSUE TITLE
Not working for me. Please support

### ISSUE THREAD

**Issue by daloki83** [fertkir/linux-utils#2]
OS: Ubuntu 22.04.1
KeePassXC: 2.6.6

Hello, i'm trying to get this tool running but so far no luck and no real error messages.
My steps:
- keepassxc-unlocker add /home/wife/OneDrive/Dokumente/PW.kdbx 
- Entered Password
- Checking Ubuntu Key-Tool and a new entry "KeepassXC Unlocker" with correct password and above mentioned path was created.
- keepassxc-unlocker autostart add

Now the tool is opening and closing keepassxc about 5 times without any interaction or opening the database. Systemctl and journalctl shows no real errors. Just complaining about too quickly start requests.

- keepassxc-unlocker unlock
Tells me, that org.freedesktop.DBUS.Error.Service Unknown. The name org.keepassxc.KeePassXC.MainWindow was not provieded by any .service file. - At that moment KeepassXC was closed.
Same command while KeepassXC is open it gives me "No such interface 'org.keepassxc.KeePassXC.MainWindow' at object path '/keepassxc'

I assume it is something with dbus-send....but no idea how to correct this.

**Comment by fertkir** [comment]
`keepassxc-unlocker-startup.service` should start the `keepassxc`. It's weird that it stops it.

Can you try running `keepassxc` in one terminal window and then `keepassxc-unlocker unlock` in another window?

**Comment by daloki83** [comment]
Thanks for supporting! Unfortunatly same result.

![Screenshot 2023-08-25 093657](https://github.com/fertkir/utils/assets/29686097/cf5b936f-a9b2-40a1-a863-390796e70a2e)

**Comment by fertkir** [comment]
I'm not sure, but this is probably related to https://github.com/keepassxreboot/keepassxc/issues/8095

Try using the latest version of KeePassXC, e.g. via Flatpak or Snap.

**Comment by daloki83** [comment]
You we're right! Update KeePassXC to 2.7.6 and the unlock command works like a charm now!

But now i have the next problem with the service after restart  :-( Any idea about that?

**Comment by daloki83** [comment]
ah i got it.
forgot to make the script available.....symlink keepassxc-unlocker into /bin/ 

Thanks for your support!
